//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeBot.Core.Model.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventState
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public string SenderId { get; set; }
        public int Direction { get; set; }
        public System.DateTime EventFrom { get; set; }
        public System.DateTime EventTo { get; set; }
    }
}
