//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeBot.Core.Model.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    
    public interface IHomeBotContext
    {
        
        DbSet<ReceivedEvent> ReceivedEvents { get; set; }
        DbSet<SentEvent> SentEvents { get; set; }
        DbSet<EventHistory> EventHistories { get; set; }
        DbSet<EventState> EventStates { get; set; }
    	Database Database { get; }
    	int SaveChanges();
    	DbEntityEntry Entry(object entity);
    }

}
	
