//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeBot.Core.Model.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SentEvent
    {
        public int Id { get; set; }
        public Nullable<int> ReceivedEventId { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public System.DateTime EventDate { get; set; }
        public string SenderId { get; set; }
        public System.DateTime SendDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ReceivedEvent ReceivedEvent { get; set; }
    }
}
